services:
  crud-caching-api:
    container_name: crud-caching-api
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    env_file: 
      - ./backend/.env
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256 --auth-local=scram-sha-256
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: